<a href="https://colab.research.google.com/github/Khushi-Kumari947/Deep-Learning/blob/main/perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub
path = kagglehub.dataset_download("darsh22blc1378/perceptron-practice")

100%|██████████| 3.11M/3.11M [00:00<00:00, 100MB/s]

Extracting files...


In [ ]:
path

'/root/.cache/kagglehub/datasets/darsh22blc1378/perceptron-practice/versions/1'

In [ ]:
import os

os.listdir(path)


['IOT.csv']

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(os.path.join(path, "IOT.csv"))
df.head()


no  id.orig_p  id.resp_p proto service  flow_duration  fwd_pkts_tot  \
0   0      38667       1883   tcp    mqtt      32.011598             9   
1   1      51143       1883   tcp    mqtt      31.883584             9   
2   2      44761       1883   tcp    mqtt      32.124053             9   
3   3      60893       1883   tcp    mqtt      31.961063             9   
4   4      51087       1883   tcp    mqtt      31.902362             9   

   bwd_pkts_tot  fwd_data_pkts_tot  bwd_data_pkts_tot  ...  active.std  \
0             5                  3                  3  ...         0.0   
1             5                  3                  3  ...         0.0   
2             5                  3                  3  ...         0.0   
3             5                  3                  3  ...         0.0   
4             5                  3                  3  ...         0.0   

      idle.min     idle.max     idle.tot     idle.avg  idle.std  \
0  29729182.96  29729182.96  29729182.96  29729182.96       0.0   
1  29855277.06  29855277.06  29855277.06  29855277.06       0.0   
2  29842149.02  29842149.02  29842149.02  29842149.02       0.0   
3  29913774.97  29913774.97  29913774.97  29913774.97       0.0   
4  29814704.90  29814704.90  29814704.90  29814704.90       0.0   

   fwd_init_window_size  bwd_init_window_size  fwd_last_window_size  \
0                 64240                 26847                   502   
1                 64240                 26847                   502   
2                 64240                 26847                   502   
3                 64240                 26847                   502   
4                 64240                 26847                   502   

    Attack_type  
0  MQTT_Publish  
1  MQTT_Publish  
2  MQTT_Publish  
3  MQTT_Publish  
4  MQTT_Publish  

[5 rows x 85 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123117 entries, 0 to 123116
Data columns (total 85 columns):
 #   Column                    Non-Null Count   Dtype  
---  ------                    --------------   -----  
 0   no                        123117 non-null  int64  
 1   id.orig_p                 123117 non-null  int64  
 2   id.resp_p                 123117 non-null  int64  
 3   proto                     123117 non-null  object 
 4   service                   123117 non-null  object 
 5   flow_duration             123117 non-null  float64
 6   fwd_pkts_tot              123117 non-null  int64  
 7   bwd_pkts_tot              123117 non-null  int64  
 8   fwd_data_pkts_tot         123117 non-null  int64  
 9   bwd_data_pkts_tot         123117 non-null  int64  
 10  fwd_pkts_per_sec          123117 non-null  float64
 11  bwd_pkts_per_sec          123117 non-null  float64
 12  flow_pkts_per_sec         123117 non-null  float64
 13  down_up_ratio             123117 non-null  f

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Attack_type']=le.fit_transform(df['Attack_type'])

In [ ]:
df['Attack_type'].unique()

array([ 3, 10, 11,  0,  1,  2,  4,  5,  6,  7,  8,  9])

In [ ]:
new_df=df.drop(columns=['proto','service'])
X=new_df.drop(columns=['Attack_type'])
y=new_df['Attack_type']

In [ ]:
X.shape,y.shape

((123117, 82), (123117,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
from sklearn.linear_model import Perceptron

In [ ]:
p=Perceptron()

In [ ]:
p.fit(X_train,y_train)

Perceptron()

In [ ]:
p.coef_

array([[-1.35671140e+07,  8.58896500e+06, -1.97526990e+07,
        -1.01404494e+04,  3.59590000e+04,  5.75000000e+02,
         2.99050000e+04, -1.14370000e+04, -3.27907075e+06,
        -6.20971368e+06, -9.48878443e+06,  1.94615457e+03,
         8.54576000e+05, -2.63040000e+04, -3.18520000e+04,
        -4.76756000e+05, -1.17280000e+04, -1.63080000e+04,
        -1.69300000e+03, -3.06400000e+03, -4.41000000e+02,
         7.88000000e+03,  1.23620000e+04, -6.45000000e+02,
        -1.90000000e+01,  0.00000000e+00, -2.61000000e+02,
        -1.67000000e+02,  1.73064000e+05,  2.00501300e+06,
         1.43776730e+07,  5.84993006e+05,  6.62155944e+05,
         6.34332000e+05,  2.92575100e+06, -3.59642790e+07,
         1.45009722e+06,  8.50499899e+05,  2.40316000e+05,
         2.95190400e+06, -2.15866060e+07,  1.02687658e+06,
         1.00175620e+06,  6.76477140e+08,  1.25329368e+09,
        -7.94445078e+09, -3.03310504e+08, -1.66775062e+09,
        -5.92287844e+08,  7.19525343e+09, -1.96956482e+0

In [ ]:
p.intercept_

array([  638., -3308.,  4874., -6013.,  -615.,    26.,    48.,  -543.,
       -7782.,   693.,   785., -2131.])

In [ ]:
from sklearn.metrics import accuracy_score
y_pred = p.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.9072829752147481
